// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwKqsCvC4FwVbXAet9cgXG6mCcQS0Rk6Q',
    appId: '1:101103803504:web:5440676dc4e41d84dbe8b5',
    messagingSenderId: '101103803504',
    projectId: 'chatbot-9821d',
    authDomain: 'chatbot-9821d.firebaseapp.com',
    storageBucket: 'chatbot-9821d.appspot.com',
    measurementId: 'G-HESVE5DRST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdYymCs9gHrMRVaVtOh-aCfjKOvXm9lWQ',
    appId: '1:101103803504:android:f6c093553ea6f14edbe8b5',
    messagingSenderId: '101103803504',
    projectId: 'chatbot-9821d',
    storageBucket: 'chatbot-9821d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOGtN3JJuNxWfDAZc0pll0_sXRPabahM',
    appId: '1:101103803504:ios:975ed08f25d5bc31dbe8b5',
    messagingSenderId: '101103803504',
    projectId: 'chatbot-9821d',
    storageBucket: 'chatbot-9821d.appspot.com',
    iosClientId: '101103803504-mvf2v1oafjvuev5pvbv75agdfete3hlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOGtN3JJuNxWfDAZc0pll0_sXRPabahM',
    appId: '1:101103803504:ios:975ed08f25d5bc31dbe8b5',
    messagingSenderId: '101103803504',
    projectId: 'chatbot-9821d',
    storageBucket: 'chatbot-9821d.appspot.com',
    iosClientId: '101103803504-mvf2v1oafjvuev5pvbv75agdfete3hlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
